### ISSUE TITLE
외부 API를 추가하기 위한 jar파일을 설정하기

### ISSUE THREAD

**Issue by xzvfinet** [CienProject2014/OneLevelHero#10]
현재는 각자의 프로젝트 core의 preference에서 jar파일을 직접 추가해주어야 한다.
하지만 build.gradle파일을 잘 수정하면 그냥 pull하는 것만으로도 사용할 수 있을 것이다.

**Comment by horace-velmont** [comment]
헤헤 끝
dependency에 compile fileTree(dir: 'libs', include: '*.jar')라는 문구를 써 주었더니 잘 됩니다

**Comment by horace-velmont** [comment]
슬프게도 재오픈

**Comment by horace-velmont** [comment]
기쁘게도 재해결
콩이 예전에 build.gradle을 삭제해서 발생한 문제였었음
