### ISSUE TITLE
WorldMap UI 재구현

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero#106]
Overlap2D를 활용해서 WorldMapUI를 재구현해보자

**Comment by horace-velmont** [comment]
WorldMapScreen2가 WorldMapStage를 가져다 쓰는 방식으로 구성하였음
추후 WorldMapScreen으로 통합할 예정

**Comment by horace-velmont** [comment]
WorldNode 클래스 재구현

**Comment by xzvfinet** [comment]
기획의 변경으로 새로운 이슈가 필요.
