### ISSUE TITLE
OptionScreen에서 SoundPopup띄우기

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero#11]
1. SoundPopup과 OptionScreen 연결하기
2. SoundPopup에서 음량을 조절하는 바를 띄울것

**Comment by NakOh** [comment]
https://github.com/alistairrutherford/tonome.git

http://www.netthreads.co.uk/2012/06/24/libgdx-audio-tonome
->soundbar참고

**Comment by horace-velmont** [comment]
알흠답다! 끝!

**Comment by horace-velmont** [comment]
1. 사운드는 전역변수로 assets에 long static 타입으로 선언해 두었으니 나중에 SoundPopup에서 리스너를 구현할때 해당 static 변수를 조절하고 (getter과 setter를 통해 <- 미구현)
2. 배경음악의 경우만 setVolume과 static변수를 둘다 조절해줄것
