### ISSUE TITLE
Battle: 유저와 비유저의 턴을 같은 방식으로 처리하기

### ISSUE THREAD

**Issue by xzvfinet** [CienProject2014/OneLevelHero#112]
같은 방식으로 처리하면, 그 이후의 작업들(중간 애니메이션 등)을 일관되게 할 수 있다.

**Comment by horace-velmont** [comment]
https://github.com/CienProject2014/OneLevelHero_ProposalTeam/issues/12#issuecomment-69881557
배달이요
