### ISSUE TITLE
VillageStage OneLevel2D로 재구성

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero#122]
지금까지의 VillageStage는 건물이나 NPC의 좌표를 직접 체크해서 뿌려주는 방식이라 블랙우드 마을외의 다른 마을도 일일이 좌표노가다를 해줘야 하는 부담이 있다. 좀더 편하게 OneLevel2D를 이용해서 배치하는 방법을 고려해보자

**Comment by xzvfinet** [comment]
이번주 내로 궁극의 "OneLevelJson" 이 완성될 예정이니, 이 이슈는 천천히 해결해주세요.

**Comment by horace-velmont** [comment]
@ChoiJIN ㄷㄷ

**Comment by horace-velmont** [comment]
119번 이슈랑 같이 병행될 예정임
