### ISSUE TITLE
GreetingScreen과 EventScreen을 팝업으로 바꾸자

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero#139]
기획팀의 기획에 따르면 NPC를 누를경우 뒷 배경이 흐려지면서 새 팝업이 뜨는 구조이다.
따라서 Screen을 팝업으로 바꾸어야한다.

**Comment by xzvfinet** [comment]
기존 스크린에 Stage를 새로 만드는 방식은 어떨까요?

**Comment by horace-velmont** [comment]
@ChoiJIN 나도 popup은 별로 쓰고 싶지 않은데 뒷배경을 흐리게하면서 새 Stage를 띄우는게 가능할까? 가능하다면 해보자
