### ISSUE TITLE
처음 메인화면에서 한글이 보이지 않습니다.

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero#14]
아무것도 보이지 않는군요 어서 고쳐주세요

**Comment by horace-velmont** [comment]
특징 1. 데스크탑상에서는 문제가 일어나지 않고 안드로이드에서만 해당 문제가 발생
2. 프롤로그 스크린에서는 똑같은 기능의 한글문구를 넣었는데 보임, MenuScreen에서만 한글이 뜨지 않음
3. 안드로이드 가상머신에서 테스트해볼 필요가 있음

**Comment by yuinacor** [comment]
영어는 뜨는데 한글만 안뜨는건지?
문자셋은 utf-8로 되어 있는지를 먼저 체크해봐야 할 듯

**Comment by horace-velmont** [comment]
모든환경 utf8이구여
데탑에선보이는데 안드에서만안보입니다
한글도 다른 스크린에서는 나오는게함정
영어는 다른스크린서는 잘 나오는데 일단테스트를
더 해봐야할것 같습니다

**Comment by NakOh** [comment]
그냥 보임
