### ISSUE TITLE
Overlap2D Runtime 리소스 해제 문제

### ISSUE THREAD

**Issue by xzvfinet** [CienProject2014/OneLevelHero#154]
Overlap2D Stage를 만들면 리소스를 다시 메모리로 로드하는 문제가 있다. 따라서 다음과 같은 해결 방법을 고려해보자.
1. 최신버전의 Overlap2D를 적용해본다.
2. Overlap2D의 GitHub에 issue를 올린다.
3. 우리가 자체적으로 수정하고, pull request를 날린다.

**Comment by horace-velmont** [comment]
#153에서 해결
