### ISSUE TITLE
Convert InitSceneLoader Into LoadSceneManager

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero#157]
InitSceneLoader는 모든 Scene을 로드하기 때문에 메모리 사용에 대한 부담을 일으킨다.
별도의 매니저를 만들어 필요시 로드하도록 만들자

**Comment by LMinJae** [comment]
https://github.com/UnderwaterApps/overlap2d-runtime-libgdx/blob/master/src/com/uwsoft/editor/renderer/resources/ResourceManager.java

project.dt에 해상도 적는게 있었네요.

저사양은 해상도도 작기 때문에 기기 해상도를 인식해서 작은걸 로드시켜도 충분할 것 같습니다.
