### ISSUE TITLE
메인 스토리 분기 트리 생성 

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero#163]
메인 스토리는 크게 6개가 있으며 6개의 트리가 서브 노드를 갖는 구조로 되어있다.
(6개의 메인 이벤트는 독립적인 구조로 되어있어서 서로 연관성을 갖지 않는다)
Json데이터로 만들어지는 이런 메인 이벤트를 트리 구조에 어떻게 집어넣을지 고려해서
설계 및 구축을 진행해보자. 자료구조는 Map을 사용할 예정

**Comment by HoraceVelmont** [comment]
메인 분기가 넘어가기 위해서는 Event에 대한 보상이 Event여야 한다.

**Comment by horace-velmont** [comment]
분기 트리거를 사용하는 분기 매니저를 만든다
분기 매니저는 처음 시작시에 한번 분기이벤트를 주입해주고 그후로는 전역으로 존재하다가 
다음 분기로 넘어갈때 개입하여 분기 이벤트를 주입하는 역할을 한다.

**Comment by horace-velmont** [comment]
#138 이슈에서 통합해서 다루겠습니다. 이부분과 같이 완성되어야 동작합니다.
