### ISSUE TITLE
SoundPopup에서 음량 조절 가능하게 하기

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero#17]
# 11의 연장선

사운드는 전역변수로 assets에 long static 타입으로 선언해 두었으니 
1. SoundPopup에서 리스너를 구현할때 getter과 setter를 통해(미구현) 해당 static 변수를 조절하고 
2. 배경음악의 경우만 setVolume과 static변수를 둘다 조절해줄것
3. 해당 슬라이더의 배치 문제 해결
4, viewport를 통한 크기 조절 (pixel값이 아닌 비율로)

**Comment by NakOh** [comment]
1. 변수조절 완료
2. 완료
3. 조정 완료
4. 크기 조절 완료
