### ISSUE TITLE
Texture 로딩 및 사용에 대한 개선

### ISSUE THREAD

**Issue by xzvfinet** [CienProject2014/OneLevelHero#182]
문제. 현재는 각 텍스쳐마다 enum을 등록해서 사용해야만 한다.
해결. 아이템을 추가하는 것은 소스에 영향을 끼치지 않아야 한다.

제안. 모든 텍스쳐를 각각 json에 추가해주는 현재의 방식 대신, 폴더 안의 파일들을 전부 읽어서 메모리에 올리는 방식을 건의한다.
이유. 현재 텍스쳐관련 json의 내용을 살펴보면, (이름으로 된 key + 경로로 된 value 쌍)으로 이루어져 있다. 하지만 이러한 정보는 굳이 json으로 만들지 않고, 폴더 자체를 읽어들이면 된다. 즉, (파일 이름 key + 파일 경로 value)로 구성해도 아무런 문제가 없다.

**Comment by LMinJae** [comment]
그러한 경우 HashMap등을 이용하여 각각의 파일이 읽어졌는지를 판단하여 동적으로 로드하는 방식의 사용도 가능할 것으로 생각됩니다.
시작 시점에서는 정말 필요한 것을 로드하고 나머지는 별도의 Thread로 처리한다면 초기 로딩에 따른 지연을 해결할수 있지 않나 생각됩니다.

**Comment by xzvfinet** [comment]
오 그것도 좋네. 근데 다시 생각해보니 폴더 단위로 로딩하는 방법을 적용할 수 없는 이유가, 나중에는 texture packer를 사용해서 하나의 파일로 관리할 계획이라.. 아마 로딩은 한 파일로 다 하고, 그것에 대한 atlas파일을 읽어서 map을 만드는 방식으로 할 것 같아.

**Comment by xzvfinet** [comment]
문제. 현재는 각 텍스쳐마다 enum을 등록해서 사용해야만 한다.
해결. 아이템을 추가하는 것은 소스에 영향을 끼치지 않아야 한다.

새로운 제안. Texture Packing된 데이터의 atlas를 읽어서 map으로 만들고 사용한다.
