### ISSUE TITLE
BattleScreen만들기

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero#19]
1. PrologueScreen -> GameScreen 연결하기
2. GameScreen에서 버튼을 누르면 BattleScreen으로 연결할 수 있도록 하기
3. Fight 기능을 구현하고 버튼을 누르면 이겼다 혹은 졌다의 로그를 출력하고 GameScreen으로 돌아간다.
4. 도망 버튼을 누르면 도망갔다의 로그를 출력하고 GameScreen으로 돌아간다.

**Comment by RANYO** [comment]
screen클래스가 아닌곳에서는 setScreen이 안먹네요. 이것저것 고민해보다 그냥 함수안에서 리턴받았어요;ㅅ;ㅎㅎ
