### ISSUE TITLE
TestLauncher로 실행했을 때 music manager에서 에러 발생

### ISSUE THREAD

**Issue by xzvfinet** [CienProject2014/OneLevelHero#201]
DesktopLauncher에서 발생하지 않는 에러가 발생한다. 
nullPointer

**Comment by horace-velmont** [comment]
그부분외에도 MusicManager는 Screen이 Prototype이기때문에 다른 스크린으로 넘어갈때마다 다시 재생된다는 문제가 있습니다. 이런 이슈들을 하나로 묶어서 MusicManager 재생 시점에 대한 논의 및 처리가 필요해보입니다.
