### ISSUE TITLE
MovingScreen + WorldMap + Village 연동

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero#22]
WorldMap에서 MovingScreen버튼을 누르면 이 클래스로 이동한다.
해당 클래스는 평상시에는 goForward()와 goBackward() 함수만 수행하지만
갈래길을 만날경우 goLeft()나 goRight()함수도 실행할 수 있다. 

이부분을 수행하는 로직 클래스는 MovingController클래스이다. 또한 BattleController에서 랜덤하게 전투와 마주치는 로직을 갖고있다. 

지금은 간단하게 랜덤하게 전투를 만났다는 로그를 뿌리고 전투를 클릭하면 BattleScreen으로 이동하는 것 정도만 구현해본다.

**Comment by nyamnym** [comment]
각 길마다 그에 맞는 이미지 할당해야  함

**Comment by horace-velmont** [comment]
헐 오브젝트화 했더니 배치가 이상해짐 ;; 소름
--> 오타로인한 버그였음

**Comment by horace-velmont** [comment]
이슈 종료하고 gradle setting후 Overlap2D로 만드는 이슈를 만들어 그 브랜치에서 활용하도록하자
