### ISSUE TITLE
MainMenu 버튼이미지 및 배경 출력

### ISSUE THREAD

**Issue by NakOh** [CienProject2014/OneLevelHero#25]

**Comment by horace-velmont** [comment]
Change/Delete/Move라벨은 클래스가 이동하거나 이름이 바뀌거나 지울때 쓰시면 됩니당

**Comment by NakOh** [comment]
버튼 위, 아래 공백 생김. 원인을 아직 파악 못함.
배경 해상도에 따라 변환되도록 손봐야함. 아직 방법을 못찾음.

**Comment by NakOh** [comment]
수정 완료!
