### ISSUE TITLE
Game UI TABLE 만들기

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero#26]
기본 테이블 만들어서 지속적으로 쓸 수 있도록 하기

**Comment by NakOh** [comment]
#2랑 연동되어 쓰는것입니까?

**Comment by horace-velmont** [comment]
@NakOh 대략그런듯 GameScreen이 없어졌으므로 2번은 닫았음

**Comment by NakOh** [comment]
GameUi ui= newGameUi()로 사용하시면 됩니다.
