### ISSUE TITLE
PrologueScreen에서 Script와 Character 크기 조절

### ISSUE THREAD

**Issue by NakOh** [CienProject2014/OneLevelHero#30]
배경화면은 해상도에 맞춰서 출력 가능.

단, 

![capture](https://cloud.githubusercontent.com/assets/7420198/3806940/4247a49e-1c59-11e4-92f3-71f56a21ab31.PNG)

에서 스크립트와 캐릭터의 크기문제 발생. 조정이 필요

**Comment by horace-velmont** [comment]
완료하였으나 스크립트의 경우 절대 크기 지정이므로 추후 상대크기 설정이 필요함.
