### ISSUE TITLE
PrologueScreen의 script 글씨 상대크기로 변경

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero#31]
1. 기기의 realSize를 가져와서 상대적으로 크기를 지정하는 방식
2. 표준 규격에 따라 case를 나누어 글씨 크기(절대크기)를 지정해주는 방식

둘중 더 나은 방식을 채택하여 글씨 크기를 설정할 것.
현재 방식은 절대크기(픽셀) 방식임.

**Comment by NakOh** [comment]
1번으로 수정 완료 아직 미세한 수정은 필요할지 몰라도 적당히 유동적임
