### ISSUE TITLE
status_item_scene 만들기

### ISSUE THREAD

**Issue by Redrock912** [CienProject2014/OneLevelHero#316]

**Comment by horace-velmont** [comment]
1. sLabels - align : 8 / 위치 조정
2. 상단의 탭이 없음
3. touchable가능한 공간이 없음
4. status_scene은 highlight기능이 없음
5. 장착 버리기 버튼 추가 요망
6. 배경 이슈

**Comment by horace-velmont** [comment]
1. description page 왼쪽정렬, 위치조정
