### ISSUE TITLE
PrologueScreen에서 사용되는 클래스를 범용적으로 수정

### ISSUE THREAD

**Issue by NakOh** [CienProject2014/OneLevelHero#32]
현재는 PrologueScreen에서만 사용할 수 있게 되어 있으므로  다른 Screen에서도 같은 클래스를 사용하여 Script 나 Background를 사용 할 수 있도록 범용적으로 수정한다.

여기서 범용적이라는건, 알기 쉬운 변수명과 누구나 쉽게 쓸 수 있는 로직을 의미한다.

**Comment by xzvfinet** [comment]
제가 가져가죠
