### ISSUE TITLE
MenuScreen에서 Load&Save 클래스로 연결

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero#4]
MenuScreen -> LoadScreen
  OptionScreen -> SaveScreen 으로
  각각 연결하기

**Comment by horace-velmont** [comment]
요구사항 수정
  MenuScreen -> LoadScreen
  OptionScreen -> SaveScreen 으로
  각각 연결하기

**Comment by NakOh** [comment]
완료
