### ISSUE TITLE
패키지 통,폐합하기

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero#40]
- UiTable -> uitable패키지 생성후 클래스이름을 UiTable로 끝나도록 변경한다. (예 : GameUiTable)
- Fight -> FightLoader과 FightController로 분리한후 각각의 패키지로 이동시킨다. (battle패키지 삭제)
- util 패키지 삭제
- VillageStage -> VillageLoader과 VillageController로 분리한 후 각각의 패키지로 이동시킨다.(stage 패키지 삭제)
- stagemanager 패키지 삭제

**Comment by horace-velmont** [comment]
지속이슈

**Comment by xzvfinet** [comment]
이런 식으로 같은 종류이지만 분리할 수 있는 이슈들은 분리하는게 흐름을 추적하기에 더 좋다고 생각합니다. close를 건의합니다

**Comment by horace-velmont** [comment]
넵 어차피 클래스구조에 따라 지속적으로 바뀔거라 이슈로 삼기는 부적합한게 맞는것 같습니다
