### ISSUE TITLE
Asset 파일 데이터 분류하기

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero#41]
현재에는 Asset 파일 구조가
- data
- prologue
- village

와 같이 되어있다 이를 좀더 의미에 맞게 분류하자
- data
  - village
  - npc
  - save
  - event
  - 기타 등등 data
- skin
  - font
  - button
  - 기타 등등.. 
- texture
  - prologue
  - village
  - 기타 등등..

**Comment by NakOh** [comment]
data 에는 .json형식의 파일만 (or MP3 파일)
Skin에는 버튼,로고등 버튼같은 곳의 skin으로 사용하는 파일들
texture에는 background처럼 이미지 자체를 사용하는 파일들
