### ISSUE TITLE
프롤로그를 보는 동안 게임 내부 시간이 진행됨

### ISSUE THREAD

**Issue by yuinacor** [CienProject2014/OneLevelHero#502]
프롤로그를 보지 않았을 때 : 오후 01시 5분
프롤로그를 봤을 때 (촌장 만나는 이벤트시) : 오전 08시

**Comment by NakOh** [comment]
프롤로그를 보지 않았을  때는 이미 앞 이벤트가 진행된 상황이기때문에 시간이 흘러가있는거로 해둔것입니당 

프롤로그를 진행하면 대충 저 시간과 비슷해지거나 좀 적습니다~

일부러 해둔 조치입니다
