### ISSUE TITLE
넥서스5 등의 soft menu buttom을 위한 immersive모드(api 16이상)

### ISSUE THREAD

**Issue by xzvfinet** [CienProject2014/OneLevelHero#54]
넥서스5는 물리버튼이 없는 대신 화면 한 쪽에 버튼 세개를 고정시켜 놓는다.

이것때문에 실제 해상도는 더 작아지고 규격에 맞지 않게 된다. 따라서 게임 실행 동안 이 메뉴 버튼들을 없애는 Immersive 모드를 동작시켜야 한다.

단, 이것은 안드로이드 4.0(api level 16)버전 이상에서만 동작하는 것이다.

**Comment by xzvfinet** [comment]
[완료] 머지해주세요 ㅋㅋㅋㅋㅋ

**Comment by horace-velmont** [comment]
커밋할때 이슈번호 뒤에 [완료]라고 써야됨 ㅋㅋㅋ
예) #54 [완료] 어쩌구저쩌구 완성
