### ISSUE TITLE
스크립트를 PrologueScreen에 할당하기

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero#6]
프롤로그 스크립트를 JSON으로 받아서
PrologueScreen.java에 뿌려줍니다.

**Comment by soyagok11** [comment]
https://drive.google.com/file/d/0B-0MK9Y1-n7JMGxVVlczVFBzYUU/edit?usp=sharing

샘플 스크립트 및 백그라운드 이미지

스크립트 위치는 일단 대충 합시다

**Comment by nyamnym** [comment]
소스트리에서 이슈 넣는거 잊었당
