### ISSUE TITLE
종료시에 dispose() 해주기

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero#65]
안드로이드에서 게임종료후 재실행시 자바의  인스턴스가 남아있곤 하는데
종료시에 일괄적으로 올라간 메모리를 dispose() 해주도록 한다.
가장 효율적인 방안을 모색해 보자

**Comment by yuinacor** [comment]
종료시에 가비지 컬렉션이 되지 않나?

자바를 사용하는데 왜 메모리 관리를 수동으로 하려고 하는지?

**Comment by horace-velmont** [comment]
@yuinacor 잘은 모르겠지만 안드로이드에서 게임 종료후 재실행시 
기존 인스턴스정보 가 남아있어 설정정보가 생성자를 통해 초기화되지 않는 현상이 발생합니다.
