### ISSUE TITLE
PrologueScreen에 이미지 띄우기

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero#7]
PrologueScreen.java에 공기토끼 이미지를 띄우고
콩의 프롤로그 대사와 어우러지게 합니다(협업필요)

**Comment by soyagok11** [comment]
https://drive.google.com/file/d/0B-0MK9Y1-n7JMGxVVlczVFBzYUU/edit?usp=sharing

샘플 스크립트 및 백그라운드 이미지

스크립트 위치는 일단 대충 합시다

**Comment by xzvfinet** [comment]
개선해주세요
