### ISSUE TITLE
UI TABLE을 쓰기 편하도록 구성하자

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero#99]
지금 UI TABLE은 개트롤이라 사이즈 조절이나 이런부분이 안된다. TABLE혹은 다른 클래스를 상속하는 클래스를 구성해서 이런부분이 편하게 조절될 수 있도록 하자

**Comment by NakOh** [comment]
Overlap2D를 도입함으로써 해결하였다.
